language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
script:  nosetests
